### PR TITLE
Super Sonic

### PR DESCRIPTION
**Pull request by DxsSucuk**
Reimplemented the functions and added the switch to the super sonic material.

### CODE REVIEW

**Comment by DS-GAMING-SE** [comment]
I want to start by thanking you for helping with my mod. I won't be merging the pull request because I don't think Super Sonic is ready to be released yet, but your solution to the material swapping will help me. However, I do kindly ask that you take down the Sonic mod you posted. If you want to make a mod built on my Sonic mod, please make my mod a hard dependency of yours. Make your mod edit my Sonic character, rather than making your own independent mod that is mostly a copy of mine.

**Comment by DxsSucuk** [comment]
Glade that I could help!
I will be taking down the Thunderstore uploaded Mod varient once I am back on a PC.

**Comment by DxsSucuk** [comment]
I completly forgot to take it down and I am sorry.
Also I could not find out how to remove it from the Thunderstore page? So I set it as depricated till I find out how to remove it.

**Comment by DxsSucuk** [comment]
The mod has now been taken down by a moderator via request!
image

**Pull request closed without merging**
